stat and resume fixes

diff --git a/cos-node-setup b/cos-node-setup
--- a/cos-node-setup
+++ b/cos-node-setup
@@ -2,8 +2,11 @@
 
 # Error handling function
 handle_error() {
- "$stage installation or execution error on $LINENO, goodbye"
-  exit 1
+echo "=========================================================="
+echo "$stage installation or execution error on $LINENO, goodbye"
+echo "=========================================================="
+sed -i /resume/s/0/1/ resume_status
+exit 1
 }
 
 # Trap errors and call the error handler
@@ -204,7 +207,7 @@ dnf upgrade -y
 dnf install -y centos-release-openstack-$release
 dnf install -y python3-openstackclient openstack-selinux
 dnf install -y python3-openstackclient openstack-selinux
-sed -i -n /basestat/s/1/0/ resume_status
+sed -i /basestat/s/1/0/ resume_status
 }
 
 mariadb_controller() {
@@ -226,7 +229,7 @@ systemctl enable --now mariadb.service
 ### mysql -e "DELETE FROM mysql.user WHERE User='';"
 ### mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
 ### mysql -e "  MariaDB> DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
-sed -i -n /mariadbstat/s/1/0/ resume_status
+sed -i /mariadbstat/s/1/0/ resume_status
 }
 
 rabbitmq_controller() {
@@ -238,7 +241,7 @@ dnf install -y rabbitmq-server
 systemctl enable --now rabbitmq-server
 rabbitmqctl add_user openstack $RABBIT_PASS
 rabbitmqctl set_permissions openstack ".*" ".*" ".*"
-sed -i -n /rabbitmqstat/s/1/0/ resume_status
+sed -i /rabbitmqstat/s/1/0/ resume_status
 }
 
 memcached_controller() {
@@ -249,7 +252,7 @@ echo "setting up memcached ..."
 dnf install -y memcached python3-memcached
 sed -i s/'OPTIONS="-l 127.0.0.1,::1"/OPTIONS="-l 127.0.0.1,::1,controller"'/ /etc/sysconfig/memcached
 systemctl enable --now memcached.service
-sed -i -n /memchachedestat/s/1/0/ resume_status
+sed -i /memcachedstat/s/1/0/ resume_status
 }
 
 etcd_all() {
@@ -272,7 +275,7 @@ ETCD_INITIAL_CLUSTER=\"controller=http://$controllerip:2380\"
 ETCD_INITIAL_CLUSTER_TOKEN=\"etcd-cluster-01\"
 ETCD_INITIAL_CLUSTER_STATE=\"new\"" >> /etc/etcd/etcd.conf
 systemctl enable --now etcd
-sed -i -n /etcdestat/s/0/1/ resume_status
+sed -i /etcdstat/s/1/0/ resume_status
 }
 
 keystone_controller() {
@@ -308,7 +311,7 @@ export OS_USER_DOMAIN_NAME=Default
 export OS_PROJECT_DOMAIN_NAME=Default
 export OS_AUTH_URL=http://controller:5000/v3
 export OS_IDENTITY_API_VERSION=3
-sed -i -n /keystonestat/s/0/1/ resume_status
+sed -i /keystonestat/s/1/0/ resume_status
 }
 
 glance_controller() {
@@ -317,9 +320,9 @@ stage=glance
 echo "setting up glance"
 
 mysql -e "CREATE DATABASE glance;"
-mysql -e "GRANT ALL PRIVILEGES ON glance.* TO \'glance'@'localhost\' \
+mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' \
   IDENTIFIED BY '$GLANCE_DBPASS';"
-mysql -e "GRANT ALL PRIVILEGES ON glance.* TO \'glance'@'%\' \
+mysql -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' \
   IDENTIFIED BY '$GLANCE_DBPASS';"
 
 echo "creating glance user ..."
@@ -354,7 +357,7 @@ echo "populating images"
 su -s /bin/sh -c "glance-manage db_sync" glance
 echo "starting daemon"
 systemctl enable --now openstack-glance-api.service
-sed -i -n /glancestat/s/1/0/ resume_status
+sed -i /glancestat/s/1/0/ resume_status
 }
 
 placement_controller()
@@ -384,7 +387,7 @@ su -s /bin/sh -c "placement-manage db sync" placement
 
 # restarting server
 systemctl restart httpd
-sed -i -n /placementstat/s/1/0/ resume_status
+sed -i /placementstat/s/1/0/ resume_status
 }
 
 nova_controller() {
@@ -457,7 +460,7 @@ systemctl start \
 openstack-nova-api.service \
 openstack-nova-scheduler.service \
 openstack-nova-conductor.service \
-sed -i -n /novactlstat/s/1/0/ resume_status
+sed -i /novactlstat/s/1/0/ resume_status
 }
 
 nova_node()
@@ -490,7 +493,7 @@ fi
 # set services up
 systemctl enable libvirtd.service openstack-nova-compute.service
 systemctl start libvirtd.service openstack-nova-compute.service
-sed -i -n /novanodestat/s/1/0/ resume_status
+sed -i /novanodestat/s/1/0/ resume_status
 
 echo "nova compute (node) set up; run the following to discover hosts manually on the controller node\nsu -s /bin/sh -c \"nova-manage cell_v2 discover_hosts --verbose\" nova"
 echo "press enter to continue"
@@ -533,7 +536,7 @@ su -s /bin/sh -c "cinder-manage db sync" cinder
 systemctl restart openstack-nova-api.service
 systemctl enable openstack-cinder-api.service openstack-cinder-scheduler.service
 systemctl start openstack-cinder-api.service openstack-cinder-scheduler.service
-sed -i -n /cinderctlstat/s/1/0/ resume_status
+sed -i /cinderctlstat/s/1/0/ resume_status
 }
 
 cinder_node()
@@ -560,7 +563,7 @@ sed -i "/^\[keystone_authtoken\]/a \nwww_authenticate_uri = http://controller:50
 systemctl enable openstack-cinder-volume.service target.service
 systemctl start openstack-cinder-volume.service target.service
 
-sed -i -n /cinderctlstat/s/1/0/ resume_status
+sed -i /cindernodestat/s/1/0/ resume_status
 }
 
 cinderbackup_node()
@@ -577,7 +580,7 @@ sed -i "/^\[DEFAULT\]/a backup_driver = cinder.backup.drivers.swift.SwiftBackupD
 systemctl enable openstack-cinder-backup.service
 systemctl start openstack-cinder-backup.service
 
-sed -i -n /cinderbackupstat/s/1/0/ resume_status
+sed -i /cinderbackupstat/s/1/0/ resume_status
 }
 
 horizon()
@@ -592,18 +595,18 @@ dnf install -y openstack-dashboard
 
 # local_settings file
 linemcd=$(awk '/^#CACHES/{ print NR }')
-sed -i -n ""$linemcd"c\#$'\t'\ \'LOCATION\':\ \'controller:11211\'," /etc/openstack-dashboard/local_settings 
+sed -i ""$linemcd"c\#$'\t'\ \'LOCATION\':\ \'controller:11211\'," /etc/openstack-dashboard/local_settings 
 sed -i "$linemcd,$(awk 'BEGIN { print $linemcd+5 }')s/^#//" /etc/openstack-dashboard/local_settings
-sed -i -n "$(awk '/^OPENSTACK_HOST/{ print NR }' /etc/openstack-dashboard/local_settings)s/127.0.0.1/controller/" /etc/openstack-dashboard/local_settings
-sed -i -n "$(awk '/^OPENSTACK_KEYSTONE_URL/{ print NR }' /etc/openstack-dashboard/local_settings)a OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True" /etc/openstack-dashboard/local_settings
-sed -i -n "$(awk '/^ALLOWED_HOSTS/{ print NR }' /etc/openstack-dashboard/local_settings)s/\'horizon.example.com\',/$(IFS="," hzallowhosts="localhost,forty.com" for x in $hzallowhosts; do echo -n "'$x', "; done)/" /etc/openstack-dashboard/local_settings
-sed -i -n "$(awk '/^OPENSTACK_KEYSTONE_URL/{ print NR }' /etc/openstack-dashboard/local_settings)a OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True\nOPENSTACK_API_VERSIONS = {\n\t\"identity\": 3,\n\t\"image\": 2,\n\t\"volume\": 3,\n}\n\nOPENSTACK_KEYSTONE_DEFAULT_DOMAIN = \"Default\"\nOPENSTACK_KEYSTONE_DEFAULT_ROLE = \"user\"" /etc/openstack-dashboard/local_settings
-sed -i -n "$(awk '/^TIME_ZONE/{ print NR }' /etc/openstack-dashboard/local_settings)s/"UTC"/$svrtz/" /etc/openstack-dashboard/local_settings
+sed -i "$(awk '/^OPENSTACK_HOST/{ print NR }' /etc/openstack-dashboard/local_settings)s/127.0.0.1/controller/" /etc/openstack-dashboard/local_settings
+sed -i "$(awk '/^OPENSTACK_KEYSTONE_URL/{ print NR }' /etc/openstack-dashboard/local_settings)a OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True" /etc/openstack-dashboard/local_settings
+sed -i "$(awk '/^ALLOWED_HOSTS/{ print NR }' /etc/openstack-dashboard/local_settings)s/\'horizon.example.com\',/$(IFS="," hzallowhosts="localhost,forty.com" for x in $hzallowhosts; do echo -n "'$x', "; done)/" /etc/openstack-dashboard/local_settings
+sed -i "$(awk '/^OPENSTACK_KEYSTONE_URL/{ print NR }' /etc/openstack-dashboard/local_settings)a OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True\nOPENSTACK_API_VERSIONS = {\n\t\"identity\": 3,\n\t\"image\": 2,\n\t\"volume\": 3,\n}\n\nOPENSTACK_KEYSTONE_DEFAULT_DOMAIN = \"Default\"\nOPENSTACK_KEYSTONE_DEFAULT_ROLE = \"user\"" /etc/openstack-dashboard/local_settings
+sed -i "$(awk '/^TIME_ZONE/{ print NR }' /etc/openstack-dashboard/local_settings)s/"UTC"/$svrtz/" /etc/openstack-dashboard/local_settings
 
 # openstack-dashboard.conf file
 sed -i "/WSGIProcessGroup\ dashboard/aWSGIApplicationGroup\ %{GLOBAL}" /etc/httpd/conf.d/openstack-dashboard.conf
 
-sed -i -n /cinderbackupstat/s/1/0/ resume_status
+sed -i /horizonstat/s/1/0/ resume_status
 }
 
 neutron_controller()
@@ -651,7 +654,7 @@ sed -i "/^\[DEFAULT\]/a interface_driver = openvswitch" /etc/neutron/l3_agent.in
 # Configure the DHCP agent¶
 sed -i "/^\[DEFAULT\]/a interface_driver = openvswitch\ndhcp_driver = neutron.agent.linux.dhcp.Dnsmasq\nenable_isolated_metadata = true" /etc/neutron/dhcp_agent.ini
 
-sed -i -n /neutronctrlstat/s/1/0/ resume_status
+sed -i /neutronctrlstat/s/1/0/ resume_status
 }
 
 neutron_compute_node()
@@ -684,7 +687,7 @@ systemctl restart openstack-nova-compute.service
 systemctl enable neutron-openvswitch-agent.service
 systemctl start neutron-openvswitch-agent.service
 
-sed -i -n /neutroncomputestat/s/1/0/ resume_status
+sed -i /neutroncomputestat/s/1/0/ resume_status
 }
 
 neutron_block_node()
@@ -704,7 +707,7 @@ mysql -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '$NEU
 srcopenrc
 openstack user create --domain default --password $NEUTRON_PASS neutron
 
-sed -i -n /neutronblockstat/s/1/0/ resume_status
+sed -i /neutronblockstat/s/1/0/ resume_status
 }
 
 swift_controller()
@@ -729,15 +732,15 @@ curl -o /etc/swift/proxy-server.conf https://opendev.org/openstack/swift/raw/bra
 sed -i '/^\[DEFAULT\]/,/^\[/{/^[^#|\[]/s/^/#\ /g}' /etc/swift/proxy-server.conf
 sed -i "/^\[DEFAULT\]/a bind_port = 8080\nuser = swift\nswift_dir = /etc/swift" /etc/swift/proxy-server.conf
 sed -i '/^\[pipeline:main\]/,/^\[/{/^[^#|\[]/s/tempurl/authtoken\ keystoneauth/; /^[^#|\[]/s/tempauth//}' /etc/swift/proxy-server.conf
-sed -i -n -e '/^\[app:proxy-server\]/,/^\[/{/egg:swift#proxy/a account_autocreate = True}' /etc/swift/proxy-server.conf
-sed -i -n -e '/\[filter:keystoneauth\]/s/^#\ //' /etc/swift/proxy-server.conf
-sed -i -n -e '/egg:swift#keystoneauth/{s/^#\ //' -e 'a operator_roles = admin,user}' /etc/swift/proxy-server.conf
-sed -i -n -e '/\[filter:authtoken\]/s/^#\ //' /etc/swift/proxy-server.conf
-sed -i -n -e "/^\[filter:authtoken\]/a paste.filter_factory = keystonemiddleware.auth_token:filter_factory\nwww_authenticate_uri = http://controller:5000\nauth_url = http://controller:5000\nmemcached_servers = controller:11211\nauth_type = password\nproject_domain_id = default\nuser_domain_id = default\nproject_name = service\nusername = swift\npassword = $SWIFT_PASS\n delay_auth_decision = True" /etc/swift/proxy-server.conf
-sed -i -n -e '/^\[filter:cache\]/,/^\[/{/egg:swift#memcache/a memcache_servers = controller:11211}' /etc/swift/proxy-server.conf
+sed -i -e '/^\[app:proxy-server\]/,/^\[/{/egg:swift#proxy/a account_autocreate = True}' /etc/swift/proxy-server.conf
+sed -i -e '/\[filter:keystoneauth\]/s/^#\ //' /etc/swift/proxy-server.conf
+sed -i -e '/egg:swift#keystoneauth/{s/^#\ //' -e 'a operator_roles = admin,user}' /etc/swift/proxy-server.conf
+sed -i -e '/\[filter:authtoken\]/s/^#\ //' /etc/swift/proxy-server.conf
+sed -i -e "/^\[filter:authtoken\]/a paste.filter_factory = keystonemiddleware.auth_token:filter_factory\nwww_authenticate_uri = http://controller:5000\nauth_url = http://controller:5000\nmemcached_servers = controller:11211\nauth_type = password\nproject_domain_id = default\nuser_domain_id = default\nproject_name = service\nusername = swift\npassword = $SWIFT_PASS\n delay_auth_decision = True" /etc/swift/proxy-server.conf
+sed -i -e '/^\[filter:cache\]/,/^\[/{/egg:swift#memcache/a memcache_servers = controller:11211}' /etc/swift/proxy-server.conf
 
 # set resume status
-sed -i -n /swiftctrlstat/s/1/0/ resume_status
+sed -i /swiftctrlstat/s/1/0/ resume_status
 }
 
 swift_node()
@@ -791,19 +794,19 @@ curl -o /etc/swift/container-server.conf https://opendev.org/openstack/swift/raw
 curl -o /etc/swift/object-server.conf https://opendev.org/openstack/swift/raw/branch/master/etc/object-server.conf-sample
 
 # account-server.conf file
-sed -i -n -e "/^\[DEFAULT\]/,/^\[/{/bind_ip/a bind_ip = $objectstoreip\nuser = swift\nswift_dir = /etc/swift\ndevices = /srv/node\nmount_check = True}" /etc/swift/account-server.conf
-sed -i -n -e "/^\[pipeline:main\]/,/^\[/{s/backend_ratelimit\ //}" /etc/swift/account-server.conf
-sed -i -n -e "/^\[filter:recon\]/,/^\[/{/egg:swift#recon/a recon_cache_path = /var/cache/swift}" /etc/swift/account-server.conf
+sed -i -e "/^\[DEFAULT\]/,/^\[/{/bind_ip/a bind_ip = $objectstoreip\nuser = swift\nswift_dir = /etc/swift\ndevices = /srv/node\nmount_check = True}" /etc/swift/account-server.conf
+sed -i -e "/^\[pipeline:main\]/,/^\[/{s/backend_ratelimit\ //}" /etc/swift/account-server.conf
+sed -i -e "/^\[filter:recon\]/,/^\[/{/egg:swift#recon/a recon_cache_path = /var/cache/swift}" /etc/swift/account-server.conf
 
 # container-server.conf
-sed -i -n -e "/^\[DEFAULT\]/,/^\[/{/bind_port/a bind_ip = $objectstoreip\nuser = swift\nswift_dir = /etc/swift\ndevices = /srv/node\nmount_check = True}" /etc/swift/container-server.conf
-sed -i -n -e "/^\[pipeline:main\]/,/^\[/{s/backend_ratelimit\ //}" /etc/swift/containter-server.conf
-sed -i -n -e "/^\[filter:recon\]/,/^\[/{/egg:swift#recon/a recon_cache_path = /var/cache/swift}" /etc/swift/account-server.conf
+sed -i -e "/^\[DEFAULT\]/,/^\[/{/bind_port/a bind_ip = $objectstoreip\nuser = swift\nswift_dir = /etc/swift\ndevices = /srv/node\nmount_check = True}" /etc/swift/container-server.conf
+sed -i -e "/^\[pipeline:main\]/,/^\[/{s/backend_ratelimit\ //}" /etc/swift/containter-server.conf
+sed -i -e "/^\[filter:recon\]/,/^\[/{/egg:swift#recon/a recon_cache_path = /var/cache/swift}" /etc/swift/account-server.conf
 
 # object-server.conf
-sed -i -n -e "/^\[DEFAULT\]/,/^\[/{/bind_port/a bind_ip = $objectstoreip\nuser = swift\nswift_dir = /etc/swift\ndevices = /srv/node\nmount_check = True}" /etc/swift/object-server.conf
-sed -i -n -e "/^\[pipeline:main\]/,/^\[/{s/backend_ratelimit\ //}" /etc/swift/object-server.conf
-sed -i -n -e "/^\[filter:recon\]/,/^\[/{/egg:swift#recon/a recon_cache_path = /var/cache/swift\nrecon_lock_path = /var/lock}" /etc/swift/object-server.conf
+sed -i -e "/^\[DEFAULT\]/,/^\[/{/bind_port/a bind_ip = $objectstoreip\nuser = swift\nswift_dir = /etc/swift\ndevices = /srv/node\nmount_check = True}" /etc/swift/object-server.conf
+sed -i -e "/^\[pipeline:main\]/,/^\[/{s/backend_ratelimit\ //}" /etc/swift/object-server.conf
+sed -i -e "/^\[filter:recon\]/,/^\[/{/egg:swift#recon/a recon_cache_path = /var/cache/swift\nrecon_lock_path = /var/lock}" /etc/swift/object-server.conf
 
 # permissions
 chown -R swift:swift /srv/node
@@ -814,7 +817,7 @@ firewall-cmd --permanent --add-port=6200/tcp
 firewall-cmd --permanent --add-port=6201/tcp
 firewall-cmd --permanent --add-port=6202/tcp
 
-sed -i -n /swiftnodestat/s/1/0/ resume_status
+sed -i /swiftnodestat/s/1/0/ resume_status
 }
 
 swift_init_rings_node()
@@ -825,9 +828,12 @@ swift-ring-builder account.builder add --region 1 --zone 1 --ip STORAGE_NODE_MAN
  --device DEVICE_NAME --weight DEVICE_WEIGHT
 
 }
+
 heat_controller()
 {
 echo "heat"
+
+sed -i /heatctrlstat/s/1/0/ resume_status
 }
 
 controller_archetype()
